"""
Django settings for pinkwaves project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jwx07$c0l*s@^f4(i)1*6ad@4%e4)fxg6-ogy1&6nr5v%j+4!8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'accounts.ExtendedUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', #rest framework
    'corsheaders', #for server security
    'knox', #knox
    'accounts.apps.AccountsConfig', #accounts
    'userMessages.apps.MessagesConfig', #messages
    'relationships.apps.RelationshipsConfig', #relationships
    'simple_email_confirmation', #for email confirmation
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', #corsheaders
    'django.middleware.common.CommonMiddleware', #corsheaders
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pinkwaves.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pinkwaves.wsgi.application'

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000'
]

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    #'DEFAULT_PERMISSION_CLASSES': [
    #    'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    #]
    'DEFAULT_AUTHENTICATION_CLASSES': (  # added
        'knox.auth.TokenAuthentication',
    )
}

#email info
from dotenv import load_dotenv
load_dotenv()
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')
EMAIL_PORT = 587
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

#states' central coordinates
STATE_COORDS = {"AL": (32.318231,-86.902298),
            "AK": (63.588753,-154.493062),
            "AZ": (34.048928,-111.093731), 
            "AR": (35.20105,-91.831833), 
            "CA": (36.778261,-119.417932), 
            "CO": (39.550051,-105.782067), 
            "CT": (41.603221,-73.087749), 
            "DC": (38.905985,-77.033418), 
            "DE": (38.910832,-75.52767), 
            "FL": (27.664827,-81.515754), 
            "GA": (32.157435,-82.907123), 
            "HI": (19.898682,-155.665857), 
            "ID": (44.068202,-114.742041), 
            "IL": (40.633125,-89.398528), 
            "IN": (40.551217,-85.602364), 
            "IA": (41.878003,-93.097702),
            "KS": (39.011902,-98.484246), 
            "KY": (37.839333,-84.270018), 
            "LA": (31.244823,-92.145024), 
            "ME": (45.253783,-69.445469), 
            "MD": (39.045755,-76.641271), 
            "MA": (42.407211,-71.382437),
            "MI": (44.314844,-85.602364),
            "MN": (46.729553,-94.6859), 
            "MS": (32.354668,-89.398528), 
            "MO": (37.964253,-91.831833),
            "MT": (46.879682,-110.362566), 
            "NE": (41.492537,-99.901813), 
            "NV": (38.80261,-116.419389), 
            "NH": (43.193852,-71.572395), 
            "NJ": (40.058324,-74.405661), 
            "NM": (34.97273,-105.032363), 
            "NY": (43.299428,-74.217933), 
            "NC": (35.759573,-79.0193),
            "ND": (47.551493,-101.002012), 
            "OH": (40.417287,-82.907123), 
            "OK": (35.007752,-97.092877),
            "OR": (43.804133,-120.554201), 
            "PA": (41.203322,-77.194525), 
            "RI": (41.580095,-71.477429), 
            "SC": (33.836081,-81.163725), 
            "SD": (43.969515,-99.901813), 
            "TN": (35.517491,-86.580447), 
            "TX": (31.968599,-99.901813), 
            "UT": (39.32098,-111.093731),
            "VT": (44.558803,-72.577841), 
            "VA": (37.431573,-78.656894),
            "WA": (47.751074,-120.740139), 
            "WV": (38.597626,-80.454903), 
            "WI": (43.78444,-88.787868), 
            "WY": (43.075968,-107.290284)
             }
